[window]
width = 900
height = 700
x = 100
y = 100

[canvas]
fog_alpha = 180

[session]
last_loaded = ""

[ui]
sidebar_visible = true

[theme]
iconAbout = "about_icon.png"
iconConfirm = "icon_confirm.png"
iconDelete = "iconic.png"
iconHealth = "health_icon.png"
iconPathCurtains = "iconic.png"
iconWarm = "warm_icon.png"
